name: Testing Binary Tree

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x', 'pypy-3.7' ]
    name: Python ${{ matrix.python-version }} Binary Tree Testing
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: |
          python binary_tree.py
          python tests/binary_tree_test.py
          python tests/search_binary_tree.py
